# Generated by Django 6.0.3 on 2026-03-29 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('source_path', models.CharField(max_length=500)),
                ('total_extracted', models.IntegerField(default=0)),
                ('total_cleaned', models.IntegerField(default=0)),
                ('total_translated', models.IntegerField(default=0)),
                ('total_deduped', models.IntegerField(default=0)),
                ('total_links_proposed', models.IntegerField(default=0)),
                ('total_published', models.IntegerField(default=0)),
                ('garbled_pages', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('awaiting_review', 'Awaiting Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='translationcache',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProposedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=500)),
                ('project_title_ne', models.CharField(blank=True, max_length=500)),
                ('project_budget', models.IntegerField(default=0)),
                ('project_neo4j_uid', models.CharField(blank=True, max_length=100)),
                ('promise_text', models.CharField(max_length=1000)),
                ('promise_neo4j_uid', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('model_used', models.CharField(default='gpt-5.4', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published to Graph')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='tracker.ingestionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
