# Generated by Django 6.0.3 on 2026-03-29 20:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_ingestionrun_alter_translationcache_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMutationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_NODE', 'Create Node'), ('UPDATE_NODE', 'Update Node'), ('DELETE_NODE', 'Delete Node'), ('CREATE_EDGE', 'Create Edge'), ('DELETE_EDGE', 'Delete Edge')], max_length=20)),
                ('node_type', models.CharField(max_length=50)),
                ('node_uid', models.CharField(max_length=100)),
                ('target_node_uid', models.CharField(blank=True, help_text='For edge mutations, the target node UID', max_length=100)),
                ('edge_type', models.CharField(blank=True, max_length=50)),
                ('property_changes', models.JSONField(default=dict, help_text='{"field": {"old": "...", "new": "..."}}')),
                ('actor', models.CharField(max_length=100)),
                ('proposed_link_id', models.UUIDField(blank=True, help_text='The ProposedLink that triggered this mutation', null=True)),
                ('evidence_refs', models.JSONField(default=list, help_text='Source document, page, extraction method')),
                ('previous_hash', models.CharField(default='GENESIS', max_length=64)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='source_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the source file for idempotency', max_length=64),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='total_flagged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='back_translated_ne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='budget_anomaly_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='budget_anomaly_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='consensus_flag',
            field=models.CharField(choices=[('agreed', '✅ Models Agreed'), ('conflict', '🔴 Models Conflicted'), ('low_consensus', '🟡 Low Consensus'), ('single_model', 'Single Model')], default='single_model', max_length=20),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='consensus_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='model_a_response',
            field=models.TextField(blank=True, help_text='GPT-5.4 reasoning'),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='model_b_response',
            field=models.TextField(blank=True, help_text='GPT-4o reasoning'),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='requires_two_reviewers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text="Reviewer's explanation"),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='second_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='second_reviewer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='translation_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='proposedlink',
            name='translation_flag',
            field=models.CharField(choices=[('ok', '✅ Verified'), ('uncertain', '⚠️ Uncertain'), ('failed', '❌ Failed')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposedlink',
            name='model_used',
            field=models.CharField(default='gpt-5.4', max_length=100),
        ),
        migrations.AlterField(
            model_name='translationcache',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
