# Generated by Django 6.0.3 on 2026-03-31 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_graphmutationlog_ingestionrun_source_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StagedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gov_level', models.CharField(choices=[('federal', 'Federal'), ('provincial', 'Provincial')], max_length=20)),
                ('province_name', models.CharField(blank=True, max_length=100)),
                ('fiscal_year', models.CharField(db_index=True, max_length=20)),
                ('source_type', models.CharField(default='lal_kitab', max_length=50)),
                ('source_document', models.CharField(max_length=500)),
                ('source_path', models.CharField(max_length=1000)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('page_num', models.IntegerField(default=0)),
                ('project_title_ne', models.CharField(max_length=500)),
                ('project_title_en', models.CharField(blank=True, max_length=500)),
                ('budget_raw', models.CharField(blank=True, max_length=120)),
                ('budget_normalized', models.BigIntegerField(default=0)),
                ('budget_hash', models.CharField(blank=True, max_length=64)),
                ('extraction_method', models.CharField(default='deterministic', max_length=40)),
                ('budget_source', models.CharField(default='deterministic', max_length=40)),
                ('translation_confidence', models.FloatField(default=1.0)),
                ('translation_flag', models.CharField(choices=[('ok', 'Verified'), ('uncertain', 'Uncertain'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('back_translated_ne', models.TextField(blank=True)),
                ('translation_model', models.CharField(blank=True, max_length=100)),
                ('translation_model_version', models.CharField(blank=True, max_length=80)),
                ('sector_slug', models.CharField(db_index=True, max_length=80)),
                ('sector_confidence', models.FloatField(default=0.0)),
                ('sector_model', models.CharField(blank=True, max_length=100)),
                ('sector_override_by', models.CharField(blank=True, max_length=100)),
                ('sector_override_reason', models.TextField(blank=True)),
                ('budget_anomaly_flag', models.BooleanField(default=False)),
                ('budget_anomaly_reason', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('worker_position', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('extra_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_projects', to='tracker.ingestionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedLinkCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_type', models.CharField(choices=[('federal_provincial', 'Federal-Provincial'), ('manifesto_alignment', 'Manifesto Alignment')], max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_candidates', to='tracker.ingestionrun')),
                ('left_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_link_candidates', to='tracker.stagedproject')),
                ('right_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_link_candidates', to='tracker.stagedproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stagedproject',
            index=models.Index(fields=['gov_level', 'province_name', 'fiscal_year'], name='tracker_sta_gov_lev_12b049_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedproject',
            index=models.Index(fields=['sector_slug', 'fiscal_year'], name='tracker_sta_sector__75d144_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedlinkcandidate',
            constraint=models.UniqueConstraint(fields=('candidate_type', 'left_project', 'right_project'), name='uniq_candidate_pair'),
        ),
    ]
