# Generated by Django 6.0.3 on 2026-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_sectortaxonomy_stagedproject_stagedlinkcandidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrun',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the source file for idempotency', max_length=64),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['source_hash', 'status'], name='tracker_ing_source__592be3_idx'),
        ),
    ]
