# Generated by Django 6.0.3 on 2026-03-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_ingestionrun_source_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedIngestionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_type", models.CharField(default="lal_kitab", max_length=50)),
                ("source_path", models.CharField(db_index=True, max_length=1000)),
                ("source_document", models.CharField(blank=True, max_length=500)),
                ("source_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("stage", models.CharField(default="ingestion", max_length=40)),
                ("failure_reason", models.CharField(max_length=255)),
                ("failure_detail", models.TextField(blank=True)),
                ("page_num", models.IntegerField(blank=True, null=True)),
                ("page_numbers", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_retry", "Pending Retry"),
                            ("retrying", "Retrying"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="pending_retry",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_items",
                        to="tracker.ingestionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="tracker_fai_status_54d00e_idx",
                    ),
                    models.Index(
                        fields=["source_hash", "status"],
                        name="tracker_fai_source__bfde94_idx",
                    ),
                    models.Index(
                        fields=["source_path", "stage"],
                        name="tracker_fai_source__38f02a_idx",
                    ),
                ],
            },
        ),
    ]
