# Generated by Django 6.0.3 on 2026-03-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_failedingestionitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="smart_ingestion_job", max_length=200)),
                ("manifest_path", models.CharField(blank=True, max_length=1000)),
                ("requested_by", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("running", "Running"),
                            ("review_hold", "Review Hold"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                            ("completed", "Completed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=50)),
                ("source_count", models.IntegerField(default=0)),
                ("processed_count", models.IntegerField(default=0)),
                ("published_count", models.IntegerField(default=0)),
                ("held_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("error_summary", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "priority"], name="tracker_ing_status_44a5fd_idx"),
                    models.Index(fields=["created_at"], name="tracker_ing_created_912cff_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.CharField(db_index=True, max_length=1000)),
                ("source_document", models.CharField(blank=True, max_length=500)),
                ("source_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lal_kitab", "Lal Kitab"),
                            ("manifesto", "Manifesto"),
                            ("media", "Media"),
                            ("citizen", "Citizen"),
                            ("other", "Other"),
                        ],
                        default="lal_kitab",
                        max_length=30,
                    ),
                ),
                (
                    "source_tier",
                    models.CharField(
                        choices=[("A", "Tier A"), ("B", "Tier B"), ("C", "Tier C")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[("tracker", "Tracker"), ("platform", "Platform"), ("both", "Both")],
                        default="tracker",
                        max_length=20,
                    ),
                ),
                ("gov_level", models.CharField(blank=True, max_length=20)),
                ("province_name", models.CharField(blank=True, max_length=100)),
                ("fiscal_year", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("extracting", "Extracting"),
                            ("publishing", "Publishing"),
                            ("review_hold", "Review Hold"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("plan_strategy", models.CharField(blank=True, max_length=40)),
                ("plan_confidence", models.FloatField(default=0.0)),
                ("plan_reason", models.TextField(blank=True)),
                ("requires_vision", models.BooleanField(default=False)),
                ("requires_ocr", models.BooleanField(default=False)),
                ("estimated_pages", models.IntegerField(default=0)),
                ("extracted_count", models.IntegerField(default=0)),
                ("published_count", models.IntegerField(default=0)),
                ("held_count", models.IntegerField(default=0)),
                ("attempt_count", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True)),
                ("payload_schema", models.CharField(blank=True, max_length=80)),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="tracker.ingestionjob"),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["job", "status"], name="tracker_ing_job_id_d970ef_idx"),
                    models.Index(fields=["source_hash", "status"], name="tracker_ing_source__8ae7a7_idx"),
                    models.Index(fields=["source_type", "status"], name="tracker_ing_source__022457_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewQueueItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("entity_type", models.CharField(default="Project", max_length=80)),
                ("record_key", models.CharField(blank=True, max_length=128)),
                ("fingerprint", models.CharField(blank=True, db_index=True, max_length=64)),
                ("proposed_payload", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("reviewer", models.CharField(blank=True, max_length=100)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items",
                        to="tracker.ingestiondocument",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items",
                        to="tracker.ingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="tracker_rev_status_239d2c_idx"),
                    models.Index(fields=["fingerprint", "status"], name="tracker_rev_fingerp_66c78a_idx"),
                ],
            },
        ),
    ]
