# Generated by Django 6.0.3 on 2026-03-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_ingestionjob_ingestiondocument_reviewqueueitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphMutationLog',
        ),
        migrations.RemoveIndex(
            model_name='ingestionrun',
            name='tracker_ing_source__592be3_idx',
        ),
        migrations.RemoveField(
            model_name='proposedlink',
            name='run',
        ),
        migrations.RemoveField(
            model_name='failedingestionitem',
            name='run',
        ),
        migrations.DeleteModel(
            name='SectorTaxonomy',
        ),
        migrations.RemoveConstraint(
            model_name='stagedlinkcandidate',
            name='uniq_candidate_pair',
        ),
        migrations.RemoveIndex(
            model_name='stagedproject',
            name='tracker_sta_gov_lev_12b049_idx',
        ),
        migrations.RemoveIndex(
            model_name='stagedproject',
            name='tracker_sta_sector__75d144_idx',
        ),
        migrations.DeleteModel(
            name='ProposedLink',
        ),
        migrations.RemoveField(
            model_name='stagedproject',
            name='run',
        ),
        migrations.DeleteModel(
            name='StagedLinkCandidate',
        ),
        migrations.DeleteModel(
            name='IngestionRun',
        ),
        migrations.DeleteModel(
            name='StagedProject',
        ),
    ]
